# Missing Values
1. Identifying missing data
2. Dropping missing data
3. Filling in missing data
4. Pandas data functions automatically ignores missing values

In [1]:
import pandas as pd 
import numpy as np
ser = pd.Series({'AAPL':0.01,'MSFT':-0.01,'TSLA':np.nan,'LULU':0.005})

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[np.nan,0.03,0.05,0.005],
      [np.nan,np.nan,-0.05,-0.0025],
      [np.nan,np.nan,np.nan,np.nan],
      [np.nan,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

## Identifying Missing Data

In [2]:
# missing data is represented by np.nan
nan=np.nan
nan

nan

In [3]:
pd.isnull(nan)

True

In [4]:
pd.isnull(5)

False

In [5]:
ser

AAPL    0.010
MSFT   -0.010
TSLA      NaN
LULU    0.005
dtype: float64

In [6]:
ser.isnull()

AAPL    False
MSFT    False
TSLA     True
LULU    False
dtype: bool

In [7]:
ser.notnull()

AAPL     True
MSFT     True
TSLA    False
LULU     True
dtype: bool

In [8]:
ser.count()

np.int64(3)

In [9]:
df.isnull()

          AAPL   MSFT   TSLA   LULU
20201201  True  False  False  False
20201202  True   True  False  False
20201203  True   True   True   True
20201204  True  False  False  False

In [10]:
df.notnull()

           AAPL   MSFT   TSLA   LULU
20201201  False   True   True   True
20201202  False  False   True   True
20201203  False  False  False  False
20201204  False   True   True   True

In [11]:
df.count()

AAPL    0
MSFT    2
TSLA    3
LULU    3
dtype: int64

## Dropping Missing Data

In [12]:
ser[ser.notnull()]

AAPL    0.010
MSFT   -0.010
LULU    0.005
dtype: float64

In [13]:
ser.dropna()

AAPL    0.010
MSFT   -0.010
LULU    0.005
dtype: float64

In [14]:
# By default dropna drops any row containing NaN
df.dropna()

Empty DataFrame
Columns: [AAPL, MSFT, TSLA, LULU]
Index: []

In [15]:
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [16]:
df.dropna(how='all')

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201204   NaN  0.015  0.03  0.0100

In [17]:
df.dropna(thresh=3)

          AAPL   MSFT  TSLA   LULU
20201201   NaN  0.030  0.05  0.005
20201204   NaN  0.015  0.03  0.010

In [18]:
df.dropna(axis=1,thresh=3)

          TSLA    LULU
20201201  0.05  0.0050
20201202 -0.05 -0.0025
20201203   NaN     NaN
20201204  0.03  0.0100

## Filling Missing Data

In [19]:
ser

AAPL    0.010
MSFT   -0.010
TSLA      NaN
LULU    0.005
dtype: float64

In [20]:
ser.fillna(0)

AAPL    0.010
MSFT   -0.010
TSLA    0.000
LULU    0.005
dtype: float64

In [21]:
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [22]:
df.fillna(0)

          AAPL   MSFT  TSLA    LULU
20201201   0.0  0.030  0.05  0.0050
20201202   0.0  0.000 -0.05 -0.0025
20201203   0.0  0.000  0.00  0.0000
20201204   0.0  0.015  0.03  0.0100

In [23]:
df.fillna({'AAPL':0.02,'TSLA':0.02,'MSFT':0.02,'LULU':0.01})

          AAPL   MSFT  TSLA    LULU
20201201  0.02  0.030  0.05  0.0050
20201202  0.02  0.020 -0.05 -0.0025
20201203  0.02  0.020  0.02  0.0100
20201204  0.02  0.015  0.03  0.0100

In [24]:
avg=df.mean()
avg

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [25]:
df.fillna(avg)

          AAPL    MSFT  TSLA      LULU
20201201   NaN  0.0300  0.05  0.005000
20201202   NaN  0.0225 -0.05 -0.002500
20201203   NaN  0.0225  0.01  0.004167
20201204   NaN  0.0150  0.03  0.010000

In [31]:
df.fillna(method='ffill',limit=1)

/var/folders/n9/h8rhghm93t97qffmcf8qqbqr0000gn/T/ipykernel_74848/393035141.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=1)

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN  0.030 -0.05 -0.0025
20201203   NaN    NaN -0.05 -0.0025
20201204   NaN  0.015  0.03  0.0100

In [32]:
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

## Pandas Functions Auto Exclude NaN

In [33]:
df.mean()

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [34]:
# only use non NaN values
df.fillna(0).sum()/df.count()

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [35]:
np.mean(df.values,1)

array([nan, nan, nan, nan])

In [36]:
df.rank()

          AAPL  MSFT  TSLA  LULU
20201201   NaN   2.0   3.0   2.0
20201202   NaN   NaN   1.0   1.0
20201203   NaN   NaN   NaN   NaN
20201204   NaN   1.0   2.0   3.0