In [1]:
import pandas as pd 
import numpy as np 

univ = ['SPY','TLT','VXX','QQQ']
dates = ['20210105','20210106','20210107','20210108','20210109']

In [2]:
earnings = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
ret_prev = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
pe = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)
analyst_est = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)

In [3]:
pe

               SPY       TLT       VXX       QQQ
20210105  1.095451 -0.718767 -0.195841 -0.325443
20210106  0.556903 -0.799933 -2.114227 -0.892272
20210107  0.434132 -0.455926 -0.403493  0.681043
20210108  1.268862  0.899106 -0.960749  1.451181
20210109 -0.918630 -0.217883  1.382188 -1.562959

In [4]:
data = {}
data['earnings']=earnings
data['ret_prev']=ret_prev
data['pe']=pe
data['analyst_est']=analyst_est

In [5]:
multi = pd.concat(data)
multi

                           SPY       TLT       VXX       QQQ
earnings    20210105 -1.729190  1.437261  0.143035 -1.023329
            20210106 -0.699894  1.020060  0.322458 -0.544643
            20210107  0.646239  1.160941 -1.124541 -0.007442
            20210108 -1.032442  0.298333 -1.008603 -0.075982
            20210109  0.436492  1.440477  0.866554  0.230933
ret_prev    20210105 -0.925389 -1.791342  2.066526 -1.484742
            20210106 -1.293040  0.579932  0.325464 -0.731860
            20210107 -0.287215 -0.293608 -2.299299 -1.527911
            20210108  0.201171 -0.840061 -0.698346  0.452329
            20210109 -0.228204 -0.642148  0.421295 -0.602597
pe          20210105  1.095451 -0.718767 -0.195841 -0.325443
            20210106  0.556903 -0.799933 -2.114227 -0.892272
            20210107  0.434132 -0.455926 -0.403493  0.681043
            20210108  1.268862  0.899106 -0.960749  1.451181
            20210109 -0.918630 -0.217883  1.382188 -1.562959
analyst_est 20210105 -0.231702 -0.548620  0.212564  1.456942
            20210106 -0.828808 -1.461064 -0.342590 -0.067557
            20210107 -1.053205 -1.231523 -1.807657  1.370147
            20210108  1.471883 -0.035810  0.697953 -1.399332
            20210109 -0.253606 -0.926466  0.358389  0.541580

In [6]:
multi.loc['pe']

               SPY       TLT       VXX       QQQ
20210105  1.095451 -0.718767 -0.195841 -0.325443
20210106  0.556903 -0.799933 -2.114227 -0.892272
20210107  0.434132 -0.455926 -0.403493  0.681043
20210108  1.268862  0.899106 -0.960749  1.451181
20210109 -0.918630 -0.217883  1.382188 -1.562959

In [7]:
multi.loc['ret_prev':'analyst_est']

                           SPY       TLT       VXX       QQQ
ret_prev    20210105 -0.925389 -1.791342  2.066526 -1.484742
            20210106 -1.293040  0.579932  0.325464 -0.731860
            20210107 -0.287215 -0.293608 -2.299299 -1.527911
            20210108  0.201171 -0.840061 -0.698346  0.452329
            20210109 -0.228204 -0.642148  0.421295 -0.602597
pe          20210105  1.095451 -0.718767 -0.195841 -0.325443
            20210106  0.556903 -0.799933 -2.114227 -0.892272
            20210107  0.434132 -0.455926 -0.403493  0.681043
            20210108  1.268862  0.899106 -0.960749  1.451181
            20210109 -0.918630 -0.217883  1.382188 -1.562959
analyst_est 20210105 -0.231702 -0.548620  0.212564  1.456942
            20210106 -0.828808 -1.461064 -0.342590 -0.067557
            20210107 -1.053205 -1.231523 -1.807657  1.370147
            20210108  1.471883 -0.035810  0.697953 -1.399332
            20210109 -0.253606 -0.926466  0.358389  0.541580

In [8]:
multi.loc[('ret_prev','20210107'),['SPY','TLT']]

SPY   -0.287215
TLT   -0.293608
Name: (ret_prev, 20210107), dtype: float64

In [9]:
ser = multi['SPY']
ser

earnings     20210105   -1.729190
             20210106   -0.699894
             20210107    0.646239
             20210108   -1.032442
             20210109    0.436492
ret_prev     20210105   -0.925389
             20210106   -1.293040
             20210107   -0.287215
             20210108    0.201171
             20210109   -0.228204
pe           20210105    1.095451
             20210106    0.556903
             20210107    0.434132
             20210108    1.268862
             20210109   -0.918630
analyst_est  20210105   -0.231702
             20210106   -0.828808
             20210107   -1.053205
             20210108    1.471883
             20210109   -0.253606
Name: SPY, dtype: float64

In [10]:
ser['pe']

20210105    1.095451
20210106    0.556903
20210107    0.434132
20210108    1.268862
20210109   -0.918630
Name: SPY, dtype: float64

In [11]:
# unstack a multindex series into a dataframe
ser.unstack(level=0)

          earnings  ret_prev        pe  analyst_est
20210105 -1.729190 -0.925389  1.095451    -0.231702
20210106 -0.699894 -1.293040  0.556903    -0.828808
20210107  0.646239 -0.287215  0.434132    -1.053205
20210108 -1.032442  0.201171  1.268862     1.471883
20210109  0.436492 -0.228204 -0.918630    -0.253606

In [12]:
ser.unstack(level=0).stack()

20210105  earnings      -1.729190
          ret_prev      -0.925389
          pe             1.095451
          analyst_est   -0.231702
20210106  earnings      -0.699894
          ret_prev      -1.293040
          pe             0.556903
          analyst_est   -0.828808
20210107  earnings       0.646239
          ret_prev      -0.287215
          pe             0.434132
          analyst_est   -1.053205
20210108  earnings      -1.032442
          ret_prev       0.201171
          pe             1.268862
          analyst_est    1.471883
20210109  earnings       0.436492
          ret_prev      -0.228204
          pe            -0.918630
          analyst_est   -0.253606
dtype: float64

In [26]:
multi = pd.concat(data, axis=1)

In [27]:
multi

          earnings                                ret_prev            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105 -1.729190  1.437261  0.143035 -1.023329 -0.925389 -1.791342
20210106 -0.699894  1.020060  0.322458 -0.544643 -1.293040  0.579932
20210107  0.646239  1.160941 -1.124541 -0.007442 -0.287215 -0.293608
20210108 -1.032442  0.298333 -1.008603 -0.075982  0.201171 -0.840061
20210109  0.436492  1.440477  0.866554  0.230933 -0.228204 -0.642148

                                    pe                                \
               VXX       QQQ       SPY       TLT       VXX       QQQ
20210105  2.066526 -1.484742  1.095451 -0.718767 -0.195841 -0.325443
20210106  0.325464 -0.731860  0.556903 -0.799933 -2.114227 -0.892272
20210107 -2.299299 -1.527911  0.434132 -0.455926 -0.403493  0.681043
20210108 -0.698346  0.452329  1.268862  0.899106 -0.960749  1.451181
20210109  0.421295 -0.602597 -0.918630 -0.217883  1.382188 -1.562959

         analyst_est
                 SPY       TLT       VXX       QQQ
20210105   -0.231702 -0.548620  0.212564  1.456942
20210106   -0.828808 -1.461064 -0.342590 -0.067557
20210107   -1.053205 -1.231523 -1.807657  1.370147
20210108    1.471883 -0.035810  0.697953 -1.399332
20210109   -0.253606 -0.926466  0.358389  0.541580

In [29]:
# indexing
multi.xs('pe', axis=1, level=0)

               SPY       TLT       VXX       QQQ
20210105  1.095451 -0.718767 -0.195841 -0.325443
20210106  0.556903 -0.799933 -2.114227 -0.892272
20210107  0.434132 -0.455926 -0.403493  0.681043
20210108  1.268862  0.899106 -0.960749  1.451181
20210109 -0.918630 -0.217883  1.382188 -1.562959

In [36]:
### multi.loc[['pe','earnings']]
idx = pd.IndexSlice
multi.loc[:, idx[['pe','earnings'], :]]

                pe                                earnings            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  1.095451 -0.718767 -0.195841 -0.325443 -1.729190  1.437261
20210106  0.556903 -0.799933 -2.114227 -0.892272 -0.699894  1.020060
20210107  0.434132 -0.455926 -0.403493  0.681043  0.646239  1.160941
20210108  1.268862  0.899106 -0.960749  1.451181 -1.032442  0.298333
20210109 -0.918630 -0.217883  1.382188 -1.562959  0.436492  1.440477


               VXX       QQQ
20210105  0.143035 -1.023329
20210106  0.322458 -0.544643
20210107 -1.124541 -0.007442
20210108 -1.008603 -0.075982
20210109  0.866554  0.230933

In [45]:
# rearrange axes
### multi.swaplevel(0,1,1)
multi.swaplevel(0, 1, axis='columns')

,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX
,analyst_est,analyst_est,analyst_est,analyst_est,earnings,earnings,earnings,earnings,pe,pe,pe,pe,ret_prev,ret_prev,ret_prev,ret_prev
20210105,1.456942,-0.231702,-0.548620,0.212564,-1.023329,-1.729190,1.437261,0.143035,-0.325443,1.095451,-0.718767,-0.195841,-1.484742,-0.925389,-1.791342,2.066526
20210106,-0.067557,-0.828808,-1.461064,-0.342590,-0.544643,-0.699894,1.020060,0.322458,-0.892272,0.556903,-0.799933,-2.114227,-0.731860,-1.293040,0.579932,0.325464
20210107,1.370147,-1.053205,-1.231523,-1.807657,-0.007442,0.646239,1.160941,-1.124541,0.681043,0.434132,-0.455926,-0.403493,-1.527911,-0.287215,-0.293608,-2.299299
20210108,-1.399332,1.471883,-0.035810,0.697953,-0.075982,-1.032442,0.298333,-1.008603,1.451181,1.268862,0.899106,-0.960749,0.452329,0.201171,-0.840061,-0.698346
20210109,0.541580,-0.253606,-0.926466,0.358389,0.230933,0.436492,1.440477,0.866554,-1.562959,-0.918630,-0.217883,1.382188,-0.602597,-0.228204,-0.642148,0.421295

In [54]:
### multi.swaplevel(0,1,1).sort_index(1)
multi.swaplevel(0, 1, axis=1).sort_index(axis=0)
### multi.swaplevel(0, 1, axis=1).sort_index(axis=1)

,analyst_est,earnings,pe,ret_prev,analyst_est,earnings,pe,ret_prev,analyst_est,earnings,pe,ret_prev,analyst_est,earnings,pe,ret_prev
,QQQ,QQQ,QQQ,QQQ,SPY,SPY,SPY,SPY,TLT,TLT,TLT,TLT,VXX,VXX,VXX,VXX
20210105,1.456942,-1.023329,-0.325443,-1.484742,-0.231702,-1.729190,1.095451,-0.925389,-0.548620,1.437261,-0.718767,-1.791342,0.212564,0.143035,-0.195841,2.066526
20210106,-0.067557,-0.544643,-0.892272,-0.731860,-0.828808,-0.699894,0.556903,-1.293040,-1.461064,1.020060,-0.799933,0.579932,-0.342590,0.322458,-2.114227,0.325464
20210107,1.370147,-0.007442,0.681043,-1.527911,-1.053205,0.646239,0.434132,-0.287215,-1.231523,1.160941,-0.455926,-0.293608,-1.807657,-1.124541,-0.403493,-2.299299
20210108,-1.399332,-0.075982,1.451181,0.452329,1.471883,-1.032442,1.268862,0.201171,-0.035810,0.298333,0.899106,-0.840061,0.697953,-1.008603,-0.960749,-0.698346
20210109,0.541580,0.230933,-1.562959,-0.602597,-0.253606,0.436492,-0.918630,-0.228204,-0.926466,1.440477,-0.217883,-0.642148,0.358389,0.866554,1.382188,0.421295

In [57]:
# sum across an axis
### multi.sum(axis=1, level=0)
multi.T.groupby(level=0).sum().T

               QQQ       SPY       TLT       VXX
20210105 -1.376573 -1.790830 -1.621468  2.226285
20210106 -2.236331 -2.264838 -0.661005 -1.808896
20210107  0.515836 -0.260049 -0.820117 -5.634989
20210108  0.428195  1.909473  0.321568 -1.969745
20210109 -1.393043 -0.963948 -0.346021  3.028426

In [63]:
# standard pandas functions produce multi-index series
### multi.mean()
multi.swaplevel(0, 1, axis=1).mean()

analyst_est  QQQ    0.380356
earnings     QQQ   -0.284093
pe           QQQ   -0.129690
ret_prev     QQQ   -0.778956
analyst_est  SPY   -0.179088
earnings     SPY   -0.475759
pe           SPY    0.487344
ret_prev     SPY   -0.506535
analyst_est  TLT   -0.840697
earnings     TLT    1.071414
pe           TLT   -0.258680
ret_prev     TLT   -0.597445
analyst_est  VXX   -0.176268
earnings     VXX   -0.160219
pe           VXX   -0.458425
ret_prev     VXX   -0.036872
dtype: float64

In [65]:
### multi.mean().unstack(level=1)
### multi.mean().unstack()
multi.mean().unstack().T

                  QQQ       SPY       TLT       VXX
analyst_est  0.380356 -0.179088 -0.840697 -0.176268
earnings    -0.284093 -0.475759  1.071414 -0.160219
pe          -0.129690  0.487344 -0.258680 -0.458425
ret_prev    -0.778956 -0.506535 -0.597445 -0.036872