# PDB - Debugging Tool

In [2]:
import pdb

for x in ['AAPL','GS']:
    
    if x == 'AAPL':
        sector = 'Tech'
        tick_sz = len(x)
    
    elif x == 'GS':
        sector = 'Fin'
        tick_sz = len(x)
    
pdb.set_trace()

> /var/folders/n9/h8rhghm93t97qffmcf8qqbqr0000gn/T/ipykernel_2535/4128564945.py(13)<module>()
      9     elif x == 'GS':
     10         sector = 'Fin'
     11         tick_sz = len(x)
     12
---> 13 pdb.set_trace()

ipdb>  c

# Rolling

In [3]:
import pandas as pd 
import numpy as np 

univ = ['AAPL','MSFT','BAC','GS']
dates = pd.date_range('20110101','20201231')
df = pd.DataFrame(np.random.randn(len(dates),len(univ)),index=dates,columns=univ)
df

                AAPL      MSFT       BAC        GS
2011-01-01  1.155920  0.156776 -0.279024 -0.370069
2011-01-02 -1.682881  0.791438 -0.593669 -1.387521
2011-01-03  0.913570  0.025346 -0.397409 -1.818965
2011-01-04 -0.080797 -0.673068  1.088808 -0.677756
2011-01-05 -1.896769 -0.244424  0.114375  0.509132
...              ...       ...       ...       ...
2020-12-27  0.737693 -0.905219  0.981399  0.524687
2020-12-28 -0.746220  0.073260  1.185295  0.317432
2020-12-29 -0.269208 -0.565195  0.392516 -0.398077
2020-12-30 -0.194410  0.672617  0.343419  1.459082
2020-12-31 -1.334702 -0.097540  0.121299  0.633367

[3653 rows x 4 columns]

In [4]:
df.rolling(252).mean()

                AAPL      MSFT       BAC        GS
2011-01-01       NaN       NaN       NaN       NaN
2011-01-02       NaN       NaN       NaN       NaN
2011-01-03       NaN       NaN       NaN       NaN
2011-01-04       NaN       NaN       NaN       NaN
2011-01-05       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...
2020-12-27  0.012480 -0.071638 -0.036576  0.016908
2020-12-28  0.010952 -0.071936 -0.031317  0.013840
2020-12-29  0.009490 -0.076245 -0.031941  0.009409
2020-12-30  0.010244 -0.078149 -0.030569  0.021289
2020-12-31 -0.002032 -0.084608 -0.027168  0.024172

[3653 rows x 4 columns]

In [6]:
df.rolling(252,min_periods=1).mean()

                AAPL      MSFT       BAC        GS
2011-01-01  1.155920  0.156776 -0.279024 -0.370069
2011-01-02 -0.263481  0.474107 -0.436347 -0.878795
2011-01-03  0.128870  0.324520 -0.423368 -1.192185
2011-01-04  0.076453  0.075123 -0.045324 -1.063578
2011-01-05 -0.318191  0.011214 -0.013384 -0.749036
...              ...       ...       ...       ...
2020-12-27  0.012480 -0.071638 -0.036576  0.016908
2020-12-28  0.010952 -0.071936 -0.031317  0.013840
2020-12-29  0.009490 -0.076245 -0.031941  0.009409
2020-12-30  0.010244 -0.078149 -0.030569  0.021289
2020-12-31 -0.002032 -0.084608 -0.027168  0.024172

[3653 rows x 4 columns]

# Quantiles

In [7]:
qcut = pd.qcut(df['AAPL'],10,labels = False)

In [8]:
qcut

2011-01-01    8
2011-01-02    0
2011-01-03    8
2011-01-04    4
2011-01-05    0
             ..
2020-12-27    7
2020-12-28    2
2020-12-29    3
2020-12-30    4
2020-12-31    0
Freq: D, Name: AAPL, Length: 3653, dtype: int64

In [9]:
qcut.value_counts().sort_index()

AAPL
0    366
1    365
2    365
3    365
4    366
5    365
6    365
7    365
8    365
9    366
Name: count, dtype: int64

In [10]:
df['AAPL'].groupby(qcut).describe()

,count,mean,std,min,25%,50%,75%,max
AAPL,,,,,,,,
0,366.0,-1.736659,0.404222,-3.734510,-1.912576,-1.652983,-1.440669,-1.298337
1,365.0,-1.072591,0.114964,-1.296976,-1.173315,-1.049258,-0.978660,-0.879273
2,365.0,-0.699433,0.101747,-0.878668,-0.788188,-0.699953,-0.608255,-0.538901
3,365.0,-0.393688,0.074148,-0.532909,-0.456713,-0.388531,-0.332371,-0.265683
4,366.0,-0.148633,0.070595,-0.263647,-0.211599,-0.151658,-0.083633,-0.024061
5,365.0,0.102468,0.075253,-0.023854,0.034409,0.100376,0.168598,0.231302
6,365.0,0.361903,0.077411,0.232216,0.293287,0.361591,0.427215,0.505687
7,365.0,0.669110,0.095207,0.506183,0.593210,0.665154,0.745995,0.842050
8,365.0,1.048713,0.125117,0.843849,0.935328,1.043000,1.152502,1.278927
9,366.0,1.740998,0.399724,1.279614,1.426844,1.654811,1.959601,3.656640

In [11]:
other_signal = pd.Series(np.random.randn(len(dates)),index=dates)
other_signal

2011-01-01   -0.424991
2011-01-02    0.676134
2011-01-03    0.987214
2011-01-04    0.157840
2011-01-05    0.087253
                ...
2020-12-27    1.054865
2020-12-28    2.249867
2020-12-29   -0.532926
2020-12-30    0.291227
2020-12-31   -1.389710
Freq: D, Length: 3653, dtype: float64

In [12]:
other_signal.groupby(qcut).mean()

AAPL
0    0.003854
1    0.028617
2    0.070692
3    0.086255
4    0.074992
5    0.033446
6   -0.164917
7   -0.001776
8   -0.002945
9   -0.000063
dtype: float64

# Shift

In [13]:
df.shift()

                AAPL      MSFT       BAC        GS
2011-01-01       NaN       NaN       NaN       NaN
2011-01-02  1.155920  0.156776 -0.279024 -0.370069
2011-01-03 -1.682881  0.791438 -0.593669 -1.387521
2011-01-04  0.913570  0.025346 -0.397409 -1.818965
2011-01-05 -0.080797 -0.673068  1.088808 -0.677756
...              ...       ...       ...       ...
2020-12-27 -0.959705  0.101403  1.100071 -0.047650
2020-12-28  0.737693 -0.905219  0.981399  0.524687
2020-12-29 -0.746220  0.073260  1.185295  0.317432
2020-12-30 -0.269208 -0.565195  0.392516 -0.398077
2020-12-31 -0.194410  0.672617  0.343419  1.459082

[3653 rows x 4 columns]

In [14]:
df / df.shift() -1

                 AAPL       MSFT       BAC         GS
2011-01-01        NaN        NaN       NaN        NaN
2011-01-02  -2.455881   4.048212  1.127661   2.749359
2011-01-03  -1.542861  -0.967975 -0.330589   0.310946
2011-01-04  -1.088441 -27.554996 -3.739768  -0.627395
2011-01-05  22.475625  -0.636851 -0.894954  -1.751203
...               ...        ...       ...        ...
2020-12-27  -1.768666  -9.926985 -0.107877 -12.011187
2020-12-28  -2.011559  -1.080931  0.207760  -0.395007
2020-12-29  -0.639238  -8.714907 -0.668845  -2.254056
2020-12-30  -0.277843  -2.190061 -0.125081  -4.665324
2020-12-31   5.865392  -1.145015 -0.646791  -0.565914

[3653 rows x 4 columns]

In [15]:
port = df
port

                AAPL      MSFT       BAC        GS
2011-01-01  1.155920  0.156776 -0.279024 -0.370069
2011-01-02 -1.682881  0.791438 -0.593669 -1.387521
2011-01-03  0.913570  0.025346 -0.397409 -1.818965
2011-01-04 -0.080797 -0.673068  1.088808 -0.677756
2011-01-05 -1.896769 -0.244424  0.114375  0.509132
...              ...       ...       ...       ...
2020-12-27  0.737693 -0.905219  0.981399  0.524687
2020-12-28 -0.746220  0.073260  1.185295  0.317432
2020-12-29 -0.269208 -0.565195  0.392516 -0.398077
2020-12-30 -0.194410  0.672617  0.343419  1.459082
2020-12-31 -1.334702 -0.097540  0.121299  0.633367

[3653 rows x 4 columns]

In [16]:
ret = df
ret

                AAPL      MSFT       BAC        GS
2011-01-01  1.155920  0.156776 -0.279024 -0.370069
2011-01-02 -1.682881  0.791438 -0.593669 -1.387521
2011-01-03  0.913570  0.025346 -0.397409 -1.818965
2011-01-04 -0.080797 -0.673068  1.088808 -0.677756
2011-01-05 -1.896769 -0.244424  0.114375  0.509132
...              ...       ...       ...       ...
2020-12-27  0.737693 -0.905219  0.981399  0.524687
2020-12-28 -0.746220  0.073260  1.185295  0.317432
2020-12-29 -0.269208 -0.565195  0.392516 -0.398077
2020-12-30 -0.194410  0.672617  0.343419  1.459082
2020-12-31 -1.334702 -0.097540  0.121299  0.633367

[3653 rows x 4 columns]

In [17]:
port_ret = (port.shift()*ret)
port_ret

                AAPL      MSFT       BAC        GS
2011-01-01       NaN       NaN       NaN       NaN
2011-01-02 -1.945276  0.124078  0.165648  0.513479
2011-01-03 -1.537431  0.020060  0.235929  2.523853
2011-01-04 -0.073814 -0.017060 -0.432702  1.232815
2011-01-05  0.153254  0.164514  0.124532 -0.345067
...              ...       ...       ...       ...
2020-12-27 -0.707967 -0.091792  1.079608 -0.025002
2020-12-28 -0.550481 -0.066316  1.163247  0.166552
2020-12-29  0.200888 -0.041406  0.465247 -0.126362
2020-12-30  0.052337 -0.380160  0.134797 -0.580827
2020-12-31  0.259480 -0.065607  0.041656  0.924134

[3653 rows x 4 columns]

In [18]:
port_ret.sum(1)

2011-01-01    0.000000
2011-01-02   -1.142071
2011-01-03    1.242412
2011-01-04    0.709239
2011-01-05    0.097233
                ...
2020-12-27    0.254847
2020-12-28    0.713002
2020-12-29    0.498366
2020-12-30   -0.773853
2020-12-31    1.159663
Freq: D, Length: 3653, dtype: float64