In [20]:
import pandas as pd 
import numpy as np 

dt = '20110109'
dt = pd.to_datetime(dt)

In [21]:
dt

Timestamp('2011-01-09 00:00:00')

In [23]:
pd.to_datetime('2011-01-09')

Timestamp('2011-01-09 00:00:00')

In [24]:
# get time fields
print (dt.year)

print (dt.month)

print (dt.day)

# maybe you care about price behavior on a particular hour, minute or second of the day?
print (dt.hour)

print (dt.minute)

print (dt.second)

2011
1
9
0
0
0

In [25]:
# useful for checking if weekend
dt.weekday()

6

In [26]:
# handles hours/minute/seconds as well
pd.to_datetime('20110107 12:10:30')

Timestamp('2011-01-07 12:10:30')

In [27]:
# convert back to a string
dt.strftime('%Y%m%d')

'20110109'

Check documentation for other string formatting codes: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [28]:
# can shift dates
dt + pd.tseries.offsets.Day()

Timestamp('2011-01-10 00:00:00')

In [30]:
# can shift by multiple time units
dt + pd.tseries.offsets.Day(1)

Timestamp('2011-01-10 00:00:00')

In [31]:
# shift only by business day (skip weekends)
dt + pd.tseries.offsets.BDay()

Timestamp('2011-01-10 00:00:00')

In [32]:
# roll forward / backward
print (pd.tseries.offsets.MonthEnd().rollforward(dt))
print (pd.tseries.offsets.MonthEnd().rollback(dt))

2011-01-31 00:00:00
2010-12-31 00:00:00

Check documentation for other offsets: https://pandas.pydata.org/docs/reference/offset_frequency.html

In [33]:
# subtract two times 
# maybe for checking days till next earnings?

dt1 = pd.to_datetime('20110101')
dt2 = pd.to_datetime('20120630')

diff = dt2 - dt1
diff

Timedelta('546 days 00:00:00')

In [34]:
diff.days

546

In [35]:
# faster way to create multiple timestamp objects. useful for converting excel dates from strings to timestamps
date = ['20110102','20110103','20110105']
dt_index = pd.DatetimeIndex(date)
dt_index

DatetimeIndex(['2011-01-02', '2011-01-03', '2011-01-05'], dtype='datetime64[ns]', freq=None)

In [36]:
dt_index[0]

Timestamp('2011-01-02 00:00:00')

In [37]:
## get time range 
days = pd.date_range(dt1,dt2,freq='D')
days

DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10',
               ...
               '2012-06-21', '2012-06-22', '2012-06-23', '2012-06-24',
               '2012-06-25', '2012-06-26', '2012-06-27', '2012-06-28',
               '2012-06-29', '2012-06-30'],
              dtype='datetime64[ns]', length=547, freq='D')

In [39]:
# can use strings as inputs and also use monthly frequency
months = pd.date_range('20110101','20121231',freq='ME')
months

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30',
               '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31',
               '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31',
               '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31',
               '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31'],
              dtype='datetime64[ns]', freq='ME')

See documentation for other frequencies: https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases

In [40]:
## DataFrames with pandas datetime index 
univ = ['SPY','TLT','VXX','QQQ']
days = pd.date_range('20190101','20210630',freq='min')
df = pd.DataFrame(np.random.randn(len(days),len(univ)),index=days,columns=univ)
df

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00  0.032762 -0.907463  0.214085 -1.228563
2019-01-01 00:01:00  2.805546  0.018930  0.353237  1.237913
2019-01-01 00:02:00 -0.102732 -0.247852  0.596005  1.752363
2019-01-01 00:03:00  2.228716 -0.049611 -0.269527  0.379399
2019-01-01 00:04:00 -0.588383  1.008095  1.943347  0.255525
...                       ...       ...       ...       ...
2021-06-29 23:56:00 -0.569816  0.442905 -2.234894  0.079063
2021-06-29 23:57:00 -0.788843 -1.656271 -0.519816 -0.915602
2021-06-29 23:58:00 -2.121709 -1.477834 -0.463973 -0.414737
2021-06-29 23:59:00  0.369369  0.000982 -0.617651  0.691367
2021-06-30 00:00:00 -0.038542  0.169001 -1.439893 -0.587629

[1311841 rows x 4 columns]

In [41]:
df.loc['2019-01-01 00:00:00']

SPY    0.032762
TLT   -0.907463
VXX    0.214085
QQQ   -1.228563
Name: 2019-01-01 00:00:00, dtype: float64

In [42]:
df.loc['2019-01-01']

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00  0.032762 -0.907463  0.214085 -1.228563
2019-01-01 00:01:00  2.805546  0.018930  0.353237  1.237913
2019-01-01 00:02:00 -0.102732 -0.247852  0.596005  1.752363
2019-01-01 00:03:00  2.228716 -0.049611 -0.269527  0.379399
2019-01-01 00:04:00 -0.588383  1.008095  1.943347  0.255525
...                       ...       ...       ...       ...
2019-01-01 23:55:00  0.679757 -1.476695 -1.037160  0.317943
2019-01-01 23:56:00 -0.314034  0.673751 -0.165279  0.862061
2019-01-01 23:57:00  0.243830  1.386483  1.769139  0.123063
2019-01-01 23:58:00 -0.744950  1.205571  0.096286  0.875054
2019-01-01 23:59:00  0.953673  1.359922  0.219043  1.726969

[1440 rows x 4 columns]

In [43]:
df.resample('M').sum()

/var/folders/n9/h8rhghm93t97qffmcf8qqbqr0000gn/T/ipykernel_2002/3731312487.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M').sum()

                   SPY         TLT         VXX         QQQ
2019-01-31 -222.196586   70.861201 -127.230342 -167.935893
2019-02-28  230.702389 -153.176797   73.035377  -64.260855
2019-03-31 -169.891599  255.117633  -11.445883 -203.697659
2019-04-30  -59.489339 -248.118052 -118.248685 -136.328907
2019-05-31  411.340827  -63.033744   28.786260 -230.003169
2019-06-30  249.263882  305.392877  -80.498827   75.904037
2019-07-31 -322.311982  -97.429805  266.131250 -112.428349
2019-08-31  -42.036992 -272.164411  -94.418223  -63.984992
2019-09-30  270.616936  157.750667  101.961865   48.121750
2019-10-31 -112.329473 -316.964930 -130.340034 -129.391217
2019-11-30 -270.484694  177.846311 -108.111372 -171.778075
2019-12-31  -72.003866 -119.565249  130.285624   28.712528
2020-01-31  522.913981  139.387862  -65.714807  351.816289
2020-02-29  305.997796  -82.000979  164.353248 -170.977821
2020-03-31 -337.996464  -16.107055  305.987392   -0.014990
2020-04-30 -361.968118  -73.857860  438.648856  -77.840763
2020-05-31  355.703148  -66.415969   -2.158067  209.705134
2020-06-30  133.553365 -173.728547   53.399551 -186.403105
2020-07-31 -223.797365 -111.816637 -190.729797 -114.285703
2020-08-31  140.039488   80.872942  389.753983 -326.392282
2020-09-30  167.731363  -39.811751  -74.126122  -53.417906
2020-10-31 -191.769740   33.993099   34.150766   67.352082
2020-11-30  -99.305889 -300.685338 -168.504235  440.384257
2020-12-31  132.650472   58.364317  195.334854   15.916500
2021-01-31  261.972542  169.290402  222.869523   44.244556
2021-02-28  211.901851    8.147809  -20.148971 -200.361221
2021-03-31  -76.584681   62.778324 -547.419490 -127.414114
2021-04-30 -193.679057  122.292920  -59.749733  190.865314
2021-05-31   -3.414522  140.332047  -63.766593  114.344717
2021-06-30   95.459697  269.726463  -85.642792  403.404490

In [44]:
# 5 minute high 
df.resample('5min').max()

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00  2.805546  1.008095  1.943347  1.752363
2019-01-01 00:05:00  1.852672  1.106063  1.177227  1.501525
2019-01-01 00:10:00  0.110978  0.857364 -0.032963  1.548546
2019-01-01 00:15:00  0.671976  1.876334  0.451995  1.457900
2019-01-01 00:20:00  0.940875  1.093324  0.803536  0.196800
...                       ...       ...       ...       ...
2021-06-29 23:40:00  1.209232  2.063126  1.392082  1.089776
2021-06-29 23:45:00  0.813397  0.774346  0.818403  1.358757
2021-06-29 23:50:00  0.450973  2.774556  0.546903  0.367363
2021-06-29 23:55:00  0.668278  0.442905  0.044177  0.691367
2021-06-30 00:00:00 -0.038542  0.169001 -1.439893 -0.587629

[262369 rows x 4 columns]

In [45]:
# close
df.resample('5min').last()

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00 -0.588383  1.008095  1.943347  0.255525
2019-01-01 00:05:00 -0.168609 -0.932863  0.524898 -2.424082
2019-01-01 00:10:00 -1.333737  0.857364 -0.032963  1.344659
2019-01-01 00:15:00  0.671976 -0.257004 -0.534294 -0.658528
2019-01-01 00:20:00  0.019705  0.029475 -0.098529  0.000539
...                       ...       ...       ...       ...
2021-06-29 23:40:00  1.082849  0.265365  1.045721 -0.502921
2021-06-29 23:45:00  0.813397 -0.073700 -1.008604  0.259482
2021-06-29 23:50:00 -1.224539  1.050856  0.370602  0.003781
2021-06-29 23:55:00  0.369369  0.000982 -0.617651  0.691367
2021-06-30 00:00:00 -0.038542  0.169001 -1.439893 -0.587629

[262369 rows x 4 columns]

Again, refer to documentation for how to specify the frequencies: https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases


Many other topics on time series in pandas not covered here!