# DataFrame Alignment
1. Arithmetic alignment between DataFrames
2. Boolean alignment between DataFrames
3. Arithmetic alignment with Series

## Arithmetic Alignment

In [1]:
import pandas as pd

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df1=pd.DataFrame(data,index=index,columns=columns)
df1

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [2]:
df2=-1.0*df1
df2

           AAPL    MSFT  TSLA    LULU
20201201  0.010 -0.0300 -0.05 -0.0050
20201202 -0.015 -0.0050  0.05  0.0025
20201203  0.025 -0.0015  0.02 -0.0100
20201204  0.030 -0.0150 -0.03 -0.0100

In [3]:
df1+df2

          AAPL  MSFT  TSLA  LULU
20201201   0.0   0.0   0.0   0.0
20201202   0.0   0.0   0.0   0.0
20201203   0.0   0.0   0.0   0.0
20201204   0.0   0.0   0.0   0.0

In [4]:
# 2D list or NumPy array

index=['20201201','20201202','20201203']
columns = ['AAPL','MSFT']

data = [[-0.005,0.01],
        [-0.025,0.0075],
        [-0.005,0.015]]
df3=pd.DataFrame(data,index=index,columns=columns)
df3

           AAPL    MSFT
20201201 -0.005  0.0100
20201202 -0.025  0.0075
20201203 -0.005  0.0150

In [5]:
df1+df3

           AAPL  LULU    MSFT  TSLA
20201201 -0.015   NaN  0.0400   NaN
20201202 -0.010   NaN  0.0125   NaN
20201203 -0.030   NaN  0.0165   NaN
20201204    NaN   NaN     NaN   NaN

In [6]:
df1.add(df3,fill_value=0)
# see also "sub","div","mul"

           AAPL    LULU    MSFT  TSLA
20201201 -0.015  0.0050  0.0400  0.05
20201202 -0.010 -0.0025  0.0125 -0.05
20201203 -0.030  0.0100  0.0165 -0.02
20201204 -0.030  0.0100  0.0150  0.03

## Boolean Alignment

In [7]:
df1>df2

           AAPL  MSFT   TSLA   LULU
20201201  False  True   True   True
20201202   True  True  False  False
20201203  False  True  False   True
20201204  False  True   True   True

In [8]:
(df1>0) & (df2>0)

           AAPL   MSFT   TSLA   LULU
20201201  False  False  False  False
20201202  False  False  False  False
20201203  False  False  False  False
20201204  False  False  False  False

In [9]:
(df1>0) | (df2>0)

          AAPL  MSFT  TSLA  LULU
20201201  True  True  True  True
20201202  True  True  True  True
20201203  True  True  True  True
20201204  True  True  True  True

## Operations b/w a Series and DataFrame are well-defined

In [10]:
df1

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [11]:
# By default arithmetic matches the index of the series on the dataframe's columns
ser = pd.Series({'AAPL':100,'MSFT':200,'TSLA':50})
df1*ser

          AAPL  LULU  MSFT  TSLA
20201201  -1.0   NaN   6.0   2.5
20201202   1.5   NaN   1.0  -2.5
20201203  -2.5   NaN   0.3  -1.0
20201204  -3.0   NaN   3.0   1.5

In [12]:
ser = pd.Series({'20201201':100,'20201203':200})
df1.mul(ser,axis=0)

          AAPL  MSFT  TSLA  LULU
20201201  -1.0   3.0   5.0   0.5
20201202   NaN   NaN   NaN   NaN
20201203  -5.0   0.3  -4.0   2.0
20201204   NaN   NaN   NaN   NaN