# DataFrame Value Retrieval

In [1]:
import pandas as pd

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [2]:
# Grab a column > returns a Series
df['AAPL']

20201201   -0.010
20201202    0.015
20201203   -0.025
20201204   -0.030
Name: AAPL, dtype: float64

In [3]:
# Grab a row > returns a Series
df.loc['20201201']

AAPL   -0.010
MSFT    0.030
TSLA    0.050
LULU    0.005
Name: 20201201, dtype: float64

In [4]:
# once you have a series, you can use regular series indexing
# grab TSLA price on 20201203

print (df['TSLA']['20201203'])
print (df.loc['20201203']['TSLA'])

-0.02
-0.02

In [5]:
# better way to grab TSLA price on 20201203 (similar to numpy 2d array)
df.loc['20201203','TSLA']

np.float64(-0.02)

In [6]:
# subset the dataframe using loc 
df.loc[['20201201','20201203'],['TSLA','AAPL']]

          TSLA   AAPL
20201201  0.05 -0.010
20201203 -0.02 -0.025

In [7]:
# can use slicing within loc
df.loc['20201201':'20201203','TSLA']

20201201    0.05
20201202   -0.05
20201203   -0.02
Name: TSLA, dtype: float64

In [8]:
# can use boolean logic within loc
df.loc[df['TSLA']>0,['TSLA','AAPL']]

          TSLA  AAPL
20201201  0.05 -0.01
20201204  0.03 -0.03

In [9]:
df.loc[:,df.loc['20201203']>0]

            MSFT    LULU
20201201  0.0300  0.0050
20201202  0.0050 -0.0025
20201203  0.0015  0.0100
20201204  0.0150  0.0100

In [10]:
df[df['AAPL']<0]

           AAPL    MSFT  TSLA   LULU
20201201 -0.010  0.0300  0.05  0.005
20201203 -0.025  0.0015 -0.02  0.010
20201204 -0.030  0.0150  0.03  0.010

In [11]:
#df<0
df[df<0]

           AAPL  MSFT  TSLA    LULU
20201201 -0.010   NaN   NaN     NaN
20201202    NaN   NaN -0.05 -0.0025
20201203 -0.025   NaN -0.02     NaN
20201204 -0.030   NaN   NaN     NaN

# DataFrame Value Modification

In [12]:
# change an entry
df.loc['20201203','TSLA']=0.03
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015  0.03  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [13]:
# set entire column to scalar
df['TSLA']=0
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300     0  0.0050
20201202  0.015  0.0050     0 -0.0025
20201203 -0.025  0.0015     0  0.0100
20201204 -0.030  0.0150     0  0.0100

In [14]:
# boolean indexing to set values
df.loc[df['AAPL']<0,'AAPL']=0
df

           AAPL    MSFT  TSLA    LULU
20201201  0.000  0.0300     0  0.0050
20201202  0.015  0.0050     0 -0.0025
20201203  0.000  0.0015     0  0.0100
20201204  0.000  0.0150     0  0.0100

In [15]:
# boolean indexing to set values
df[df<0]=0
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300     0  0.005
20201202  0.015  0.0050     0  0.000
20201203  0.000  0.0015     0  0.010
20201204  0.000  0.0150     0  0.010

In [16]:
# set column using list (of same size as column)
df['TSLA']=[0.05,-0.05,-0.2,0.03]
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300  0.05  0.005
20201202  0.015  0.0050 -0.05  0.000
20201203  0.000  0.0015 -0.20  0.010
20201204  0.000  0.0150  0.03  0.010

In [17]:
df['TSLA']=[0.05,-0.05,-0.2] # error
df

ValueError: Length of values (3) does not match length of index (4)

In [18]:
# set column using series > automatically aligns indices
# doesn't need to be the same size
tsla = pd.Series({'20201204':0.01,'20201201':0.02,'20201202':0.04})
tsla

20201204    0.01
20201201    0.02
20201202    0.04
dtype: float64

In [19]:
df['TSLA']=tsla
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300  0.02  0.005
20201202  0.015  0.0050  0.04  0.000
20201203  0.000  0.0015   NaN  0.010
20201204  0.000  0.0150  0.01  0.010

In [20]:
# set a row 
df.loc['20201202']=[0.01,0.02,0.03,0.04]
df

          AAPL    MSFT  TSLA   LULU
20201201  0.00  0.0300  0.02  0.005
20201202  0.01  0.0200  0.03  0.040
20201203  0.00  0.0015   NaN  0.010
20201204  0.00  0.0150  0.01  0.010

In [21]:
# set a subset of a df
df.loc[['20201202','20201203'],['AAPL','TSLA']]

          AAPL  TSLA
20201202  0.01  0.03
20201203  0.00   NaN

In [22]:
df.loc[['20201202','20201203'],['AAPL','TSLA']]=[[0.01,-0.01],[0.02,0.03]]
df

          AAPL    MSFT  TSLA   LULU
20201201  0.00  0.0300  0.02  0.005
20201202  0.01  0.0200 -0.01  0.040
20201203  0.02  0.0015  0.03  0.010
20201204  0.00  0.0150  0.01  0.010

In [23]:
# create a new column
df['XOM']=[0.01,0.005,-0.005,0.025]
df

          AAPL    MSFT  TSLA   LULU    XOM
20201201  0.00  0.0300  0.02  0.005  0.010
20201202  0.01  0.0200 -0.01  0.040  0.005
20201203  0.02  0.0015  0.03  0.010 -0.005
20201204  0.00  0.0150  0.01  0.010  0.025

In [24]:
# create a new row 
df.loc['20201205']=[-0.01,0.015,0.03,0.05,-0.01]
df

          AAPL    MSFT  TSLA   LULU    XOM
20201201  0.00  0.0300  0.02  0.005  0.010
20201202  0.01  0.0200 -0.01  0.040  0.005
20201203  0.02  0.0015  0.03  0.010 -0.005
20201204  0.00  0.0150  0.01  0.010  0.025
20201205 -0.01  0.0150  0.03  0.050 -0.010